### ISSUE TITLE
Crash in mail module

### ISSUE THREAD

**Issue by ltworf** [ltworf/ltdata#19]
```
Replying
Replying mail: no new messages
( selvin ) some_fucher: !mail selvin

Replying
Traceback (most recent call last):
  File "./bot.py", line 209, in <module>
    main()
  File "./bot.py", line 193, in main
    reply(nick, destination, message, sock)
  File "./bot.py", line 53, in reply
    r = i.sendmsg(sender, recip, text.decode('utf-8'))
  File "/home/salvo/dev/ltdata/modules/mail.py", line 73, in sendmsg
    _, mbox, msg = args
ValueError: need more than 2 values to unpack
```

**Comment by ltworf** [comment]
Fixed
